name: Build GameBoy WebAssembly

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto y submodulos
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Crear carpeta ROMs
        run: mkdir -p ROMs

      - name: Compilar solamente WebAssembly
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target wasm --parallel 1

      - name: Verificar WebAssembly
        run: |
          test -f www/static/gameboy.js
          test -f www/static/gameboy.wasm
          ls -lh www/static/gameboy.js
          ls -lh www/static/gameboy.wasm

      - name: Instalar Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compilar web Fresh
        working-directory: www
        run: |
          deno install
          deno task build

      - name: Verificar build Fresh
        run: |
          test -f www/_fresh/server.js
          echo "Build Fresh generado correctamente:"
          ls -lah www/_fresh

      - name: Guardar build completo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f www/static/gameboy.js
          git add -f www/static/gameboy.wasm
          git add -f www/_fresh

          if git diff --cached --quiet; then
            echo "El build ya estaba actualizado."
          else
            git commit -m "Build web completa"
            git push origin HEAD:main
          fi
