name: Build and Deploy GameBoy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto principal
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main

      - name: Descargar ROMs privadas
        uses: actions/checkout@v4
        with:
          repository: GuillermoAndria/gameboy-roms
          token: ${{ secrets.ROMS_TOKEN }}
          path: ROMs

      - name: Verificar ROM privada
        run: |
          test -f ROMs/pokemon-red.gb
          echo "pokemon-red.gb encontrada correctamente"

      - name: Limpiar ROMs publicas del workspace
        run: |
          rm -rf www/static/roms
          mkdir -p www/static/roms

      - name: Compilar WebAssembly
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target wasm --parallel 1

      - name: Verificar archivos generados
        run: |
          test -f www/static/gameboy.js
          test -f www/static/gameboy.wasm
          test -f www/static/roms/pokemon-red.gb

          echo "Archivos listos:"
          ls -lh www/static/gameboy.js
          ls -lh www/static/gameboy.wasm
          ls -lh www/static/roms/pokemon-red.gb

      - name: Instalar Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Instalar dependencias
        working-directory: www
        run: deno install

      - name: Compilar Fresh
        working-directory: www
        run: deno task build

      - name: Verificar Fresh
        run: |
          test -f www/_fresh/server.js
          echo "Fresh compilado correctamente"

      - name: Desplegar en Deno Deploy
        working-directory: www
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          deno deploy \
            --org gameboy2 \
            --app gameboy \
            --prod
